name: Test with Caching

on:
  workflow_dispatch:

jobs:
  test-with-cache:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Cache long task result
      id: cache-result
      uses: actions/cache@v3
      with:
        path: ./result.txt
        key: ${{ runner.os }}-long-task-result-${{ github.sha }}

    - name: Run long task if cache miss
      if: steps.cache-result.outputs.cache-hit != 'true'
      run: |
        echo "Running long task..."
        sleep 30  # Simulate a long-running task
        echo "Long task completed at $(date)" > result.txt

    - name: Use result
      run: cat result.txt