name: Install and Cache Tool

on:
  workflow_dispatch:

jobs:
  install-and-use-tool:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Debug ls of ~/.local
      run: |
        ls -la ~/.local/lib || echo "Directory does not exist"

    - name: Cache installed tool
      id: cache-tool
      uses: actions/cache@v3
      with:
        path: ~/.local/lib
        key: ${{ runner.os }}-my-tool-${{ hashFiles('~/.local/**/*') }}

    - name: Install tool if cache miss
      if: steps.cache-tool.outputs.cache-hit != 'true'
      run: |
        pip install --user azure-cli 
    
    - name: Debug ls of ~/.local after installation
      run: |
        ls -la ~/.local/lib || echo "Directory does not exist"

    - name: Use tool
      run: az --version

    - name: Where the F is it ?
      run: |
       which az
       python -m site --user-site