name: Install and Cache Tool

on:
  workflow_dispatch:

jobs:
  install-and-use-tool:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Debug ls of ~/.local/share/my-tool
      run: |
        ls -la ~/.local/share/my-tool || echo "Directory does not exist"

    - name: Cache installed tool
      id: cache-tool
      uses: actions/cache@v3
      with:
        path: ~/.local/share/my-tool
        key: ${{ runner.os }}-my-tool-${{ hashFiles('~/.local/share/azure-cli/**') }}

    - name: Install tool if cache miss
      if: steps.cache-tool.outputs.cache-hit != 'true'
      run: |
        pip install --target=~/.local/share/my-tool azure-cli 
    
    - name: Debug ls of ~/.local/share/my-tool after installation
      run: |
        ls -la ~/.local/share/my-tool || echo "Directory does not exist"

    - name: Add tool to PATH
      run: echo "$HOME/.local/share/my-tool/bin" >> $GITHUB_PATH

    - name: Use tool
      run: az --version